"""Write a readable Markdown snapshot of what the agent knows: ranked opportunities, programs with sources,
resume checks and the skills roadmap. Contains no contact details.

    python scripts/export_snapshot.py ../docs/RESEARCH_SNAPSHOT.md
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select  # noqa: E402

from app.db import SessionLocal  # noqa: E402
from app.models import Company, Job, Program  # noqa: E402
from app.services.classify import GRAD_LABELS  # noqa: E402
from app.services.evidence import evidence_for, grouped  # noqa: E402
from app.services.profile import master_resume  # noqa: E402
from app.services.research import FIELDS  # noqa: E402
from app.services.scoring import CATEGORY_LABELS  # noqa: E402
from app.services.skills_gap import roadmap  # noqa: E402
from app.util import today  # noqa: E402

KEY_FIELDS = ["program.description", "program.duration", "program.location", "program.work_mode", "comp.base",
              "program.training_content", "program.rotations", "program.mentorship", "program.next_role",
              "program.conversion", "program.outcomes", "program.eligibility", "program.technical_req", "program.yoe",
              "program.start_date", "program.open_window", "program.rolling", "travel.percent"]


def main(out: str) -> None:
    db = SessionLocal()
    L = [f"# Research snapshot ({today():%B %d, %Y})", "",
         "Generated by the agent from its database. Every program fact carries its source type and confidence. "
         "Seeded postings must be re-verified live (run Find new jobs) before you rely on them.", ""]
    res = master_resume(db)
    if res:
        L += ["## Resume checks", ""]
        for c in res.checks:
            if c["severity"] in ("high", "medium"):
                L.append(f"- **{c['severity'].title()}:** {c['message']}")
        L.append("")
    L += ["## Opportunities by category", ""]
    for cat, title in CATEGORY_LABELS.items():
        jobs = list(db.scalars(select(Job).where(Job.category == cat, Job.hidden.is_(False)).order_by(Job.score_total.desc())))
        if not jobs:
            continue
        L += [f"### {title}", "", "| Fit | Path | Company | Role | Where | Timing |", "|---|---|---|---|---|---|"]
        for j in jobs:
            L.append(f"| {j.score_total:.0f} | {j.path_class} | {j.company.name} | {j.title} | {j.location_text or ''} | "
                     f"{GRAD_LABELS.get(j.grad_status, j.grad_status)} |")
        L.append("")
        top = jobs[0]
        L.append(f"Why the top one scored {top.score_total:.0f}: " + "; ".join(
            f"{c['label']} {c['score']}/{c['max']:.0f}" for c in top.score_breakdown.values()) + ".")
        L.append("")
    L += ["## Programs", ""]
    for fam, title in (("se", "Programs that train you into SE"), ("mixed", "Rotational programs"),
                       ("ae", "Sales academies (lead to Account Executive)")):
        progs = list(db.scalars(select(Program).where(Program.target_family == fam)))
        if not progs:
            continue
        L += [f"### {title}", ""]
        for p in progs:
            L += [f"#### {p.company.name}: {p.name}", "", p.summary or "", ""]
            g = grouped(evidence_for(db, "program", p.id))
            for field in KEY_FIELDS:
                for f in g.get(field, [])[:2]:
                    src = f"[{f['source']['title'] or 'source'}]({f['source']['url']})" if f["source"] else "no source"
                    L.append(f"- **{FIELDS.get(field, field)}:** {f['value']} *({f['source_type'].replace('_', ' ')}, "
                             f"{f['confidence']} confidence; {src})*")
            for c in (p.data or {}).get("concerns", []):
                L.append(f"- **Concern:** {c}")
            L.append("")
    rm = roadmap(db)
    L += ["## Skills roadmap", ""]
    for s in rm["stages"]:
        L.append(f"- **{s['stage']}: {s['area']}.** {s['why']}")
    L += ["", "## Watchlist", ""]
    for c in db.scalars(select(Company).where(Company.watch_status.is_not(None)).order_by(Company.watch_status, Company.name)):
        L.append(f"- **{c.name}** ({c.watch_status.replace('_', ' ')}){': ' + c.watch_note if c.watch_note else ''}")
    Path(out).write_text("\n".join(L).replace("\u2014", ", ") + "\n")
    print(f"wrote {out} ({len(L)} lines)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "RESEARCH_SNAPSHOT.md")
